
package br.univel.wsclient.entrega;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EntregaJaxWS", targetNamespace = "http://webservice.univel.br/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EntregaJaxWS {


    /**
     * 
     * @return
     *     returns br.univel.wsclient.entrega.Entrega
     * @throws IOException_Exception
     * @throws ServletException_Exception
     */
    @WebMethod
    @WebResult(name = "resultadoEntrega", targetNamespace = "")
    @RequestWrapper(localName = "operacaoEntrega", targetNamespace = "http://webservice.univel.br/", className = "br.univel.wsclient.entrega.OperacaoEntrega")
    @ResponseWrapper(localName = "operacaoEntregaResponse", targetNamespace = "http://webservice.univel.br/", className = "br.univel.wsclient.entrega.OperacaoEntregaResponse")
    public Entrega operacaoEntrega()
        throws IOException_Exception, ServletException_Exception
    ;

}
