
package br.univel.wsclient.crudproduto;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CadastroProdutoJaxWSService", targetNamespace = "http://webservice.univel.br/", wsdlLocation = "http://localhost:8080/lab135402/CadastroProdutoJaxWS?WSDL")
public class CadastroProdutoJaxWSService
    extends Service
{

    private final static URL CADASTROPRODUTOJAXWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException CADASTROPRODUTOJAXWSSERVICE_EXCEPTION;
    private final static QName CADASTROPRODUTOJAXWSSERVICE_QNAME = new QName("http://webservice.univel.br/", "CadastroProdutoJaxWSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/lab135402/CadastroProdutoJaxWS?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CADASTROPRODUTOJAXWSSERVICE_WSDL_LOCATION = url;
        CADASTROPRODUTOJAXWSSERVICE_EXCEPTION = e;
    }

    public CadastroProdutoJaxWSService() {
        super(__getWsdlLocation(), CADASTROPRODUTOJAXWSSERVICE_QNAME);
    }

    public CadastroProdutoJaxWSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CADASTROPRODUTOJAXWSSERVICE_QNAME, features);
    }

    public CadastroProdutoJaxWSService(URL wsdlLocation) {
        super(wsdlLocation, CADASTROPRODUTOJAXWSSERVICE_QNAME);
    }

    public CadastroProdutoJaxWSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CADASTROPRODUTOJAXWSSERVICE_QNAME, features);
    }

    public CadastroProdutoJaxWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CadastroProdutoJaxWSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CadastroProdutoJaxWS
     */
    @WebEndpoint(name = "CadastroProdutoJaxWSPort")
    public CadastroProdutoJaxWS getCadastroProdutoJaxWSPort() {
        return super.getPort(new QName("http://webservice.univel.br/", "CadastroProdutoJaxWSPort"), CadastroProdutoJaxWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CadastroProdutoJaxWS
     */
    @WebEndpoint(name = "CadastroProdutoJaxWSPort")
    public CadastroProdutoJaxWS getCadastroProdutoJaxWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.univel.br/", "CadastroProdutoJaxWSPort"), CadastroProdutoJaxWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CADASTROPRODUTOJAXWSSERVICE_EXCEPTION!= null) {
            throw CADASTROPRODUTOJAXWSSERVICE_EXCEPTION;
        }
        return CADASTROPRODUTOJAXWSSERVICE_WSDL_LOCATION;
    }

}
