
package br.univel.wsclient.crudproduto;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CadastroProdutoJaxWS", targetNamespace = "http://webservice.univel.br/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CadastroProdutoJaxWS {


    /**
     * 
     * @param produtoId
     */
    @WebMethod
    @RequestWrapper(localName = "deletarProduto", targetNamespace = "http://webservice.univel.br/", className = "br.univel.wsclient.crudproduto.DeletarProduto")
    @ResponseWrapper(localName = "deletarProdutoResponse", targetNamespace = "http://webservice.univel.br/", className = "br.univel.wsclient.crudproduto.DeletarProdutoResponse")
    public void deletarProduto(
        @WebParam(name = "produtoId", targetNamespace = "")
        Long produtoId);

    /**
     * 
     * @return
     *     returns java.util.List<br.univel.wsclient.crudproduto.Produto>
     */
    @WebMethod
    @WebResult(name = "retornoListaProduto", targetNamespace = "")
    @RequestWrapper(localName = "listaProduto", targetNamespace = "http://webservice.univel.br/", className = "br.univel.wsclient.crudproduto.ListaProduto")
    @ResponseWrapper(localName = "listaProdutoResponse", targetNamespace = "http://webservice.univel.br/", className = "br.univel.wsclient.crudproduto.ListaProdutoResponse")
    public List<Produto> listaProduto();

    /**
     * 
     * @param produto
     */
    @WebMethod
    @RequestWrapper(localName = "criarProduto", targetNamespace = "http://webservice.univel.br/", className = "br.univel.wsclient.crudproduto.CriarProduto")
    @ResponseWrapper(localName = "criarProdutoResponse", targetNamespace = "http://webservice.univel.br/", className = "br.univel.wsclient.crudproduto.CriarProdutoResponse")
    public void criarProduto(
        @WebParam(name = "produto", targetNamespace = "")
        Produto produto);

    /**
     * 
     * @param produto
     */
    @WebMethod
    @RequestWrapper(localName = "alterarProduto", targetNamespace = "http://webservice.univel.br/", className = "br.univel.wsclient.crudproduto.AlterarProduto")
    @ResponseWrapper(localName = "alterarProdutoResponse", targetNamespace = "http://webservice.univel.br/", className = "br.univel.wsclient.crudproduto.AlterarProdutoResponse")
    public void alterarProduto(
        @WebParam(name = "produto", targetNamespace = "")
        Produto produto);

}
