
package br.univel.wsclient.venda;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "VendaJaxWS", targetNamespace = "http://webservice.univel.br/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface VendaJaxWS {


    /**
     * 
     * @return
     *     returns br.univel.wsclient.venda.Venda
     * @throws IOException_Exception
     * @throws ServletException_Exception
     */
    @WebMethod
    @WebResult(name = "resultadoVenda", targetNamespace = "")
    @RequestWrapper(localName = "operacaoVenda", targetNamespace = "http://webservice.univel.br/", className = "br.univel.wsclient.venda.OperacaoVenda")
    @ResponseWrapper(localName = "operacaoVendaResponse", targetNamespace = "http://webservice.univel.br/", className = "br.univel.wsclient.venda.OperacaoVendaResponse")
    public Venda operacaoVenda()
        throws IOException_Exception, ServletException_Exception
    ;

}
